SET FOREIGN_KEY_CHECKS=0;




CREATE TABLE MAU_CotizacionAuto
(
	CAU_Id INTEGER NOT NULL AUTO_INCREMENT,
	COT_Id INTEGER,
	MOD_Id INTEGER,
	CAU_FechaCotizacion DATETIME,
	CAU_ModeloAnio INTEGER,
	CAU_Propietario BOOL,
	COM_Id INTEGER,
	PAR_IdUso INTEGER,
	PAR_IdTipoVehiculo INTEGER,
	PER_Id INTEGER,
	CAU_Eliminado BOOL,
	PRIMARY KEY (CAU_Id),
	KEY (COT_Id),
	KEY (COM_Id),
	KEY (PER_Id),
	KEY (MOD_Id)
) 
;


CREATE TABLE MAU_Marca
(
	MAR_Id INTEGER NOT NULL AUTO_INCREMENT,
	MAR_Nombre VARCHAR(200),
	MAR_Eliminado BOOL,
	PRIMARY KEY (MAR_Id)
) 
;


CREATE TABLE MAU_MarcaId
(
	MMA_Id INTEGER NOT NULL AUTO_INCREMENT,
	MAR_Id INTEGER,
	ECO_Id INTEGER,
	PRIMARY KEY (MMA_Id),
	KEY (MAR_Id),
	KEY (ECO_Id)
) 
;


CREATE TABLE MAU_Modelo
(
	MOD_Id INTEGER NOT NULL AUTO_INCREMENT,
	MOD_Nombre VARCHAR(200),
	MOD_Eliminado BOOL,
	MAR_Id INTEGER,
	PRIMARY KEY (MOD_Id),
	KEY (MAR_Id)
) 
;


CREATE TABLE MAU_ModeloId
(
	MMO_Id INTEGER NOT NULL AUTO_INCREMENT,
	MOD_Id INTEGER,
	ECO_Id INTEGER,
	PRIMARY KEY (MMO_Id),
	KEY (MOD_Id),
	KEY (ECO_Id)
) 
;


CREATE TABLE MPS_AseguradoraId
(
	AID_Id INTEGER NOT NULL AUTO_INCREMENT,
	EAS_Id INTEGER,
	ECO_Id INTEGER,
	PRIMARY KEY (AID_Id),
	KEY (EAS_Id),
	KEY (ECO_Id)
) 
;


CREATE TABLE MPS_Ciudad
(
	CIU_Id INTEGER NOT NULL AUTO_INCREMENT,
	CIU_Codigo INTEGER,
	CIU_Nombre VARCHAR(250),
	REG_Id INTEGER,
	CIU_Eliminado BOOL,
	PRIMARY KEY (CIU_Id),
	KEY (REG_Id)
) 
;


CREATE TABLE MPS_Comuna
(
	COM_Id INTEGER NOT NULL AUTO_INCREMENT,
	COM_Codigo INTEGER,
	COM_Nombre VARCHAR(250),
	REG_Id INTEGER,
	CIU_Id INTEGER,
	COM_Eliminado BOOL,
	PRIMARY KEY (COM_Id),
	KEY (CIU_Id),
	KEY (REG_Id)
) 
;


CREATE TABLE MPS_Cotizacion
(
	COT_Id INTEGER NOT NULL AUTO_INCREMENT,
	COT_Numero VARCHAR(250),
	COT_Codigo VARCHAR(250),
	PRO_Id INTEGER,
	ECO_Id INTEGER,
	COT_ErrorId INTEGER,
	COT_ErrorMensaje VARCHAR(250),
	COT_Eliminado BOOL,
	PRIMARY KEY (COT_Id),
	KEY (PRO_Id),
	KEY (ECO_Id)
) 
;


CREATE TABLE MPS_CotizacionOferta
(
	COF_Id INTEGER NOT NULL AUTO_INCREMENT,
	COT_Id INTEGER,
	COF_Deducible INTEGER,
	COF_PrimaAfecta FLOAT(0),
	COF_PrimaExenta FLOAT(0),
	COF_PrimaIva FLOAT(0),
	COF_PrimaBruta FLOAT(0),
	COF_ValorCuota FLOAT(0),
	COF_NumeroCuotas INTEGER,
	COF_PromocionId INTEGER,
	EAS_Id INTEGER,
	COF_Eliminado BOOL,
	PRIMARY KEY (COF_Id),
	KEY (EAS_Id),
	KEY (COT_Id)
) 
;


CREATE TABLE MPS_EmpresaAseguradora
(
	EAS_Id INTEGER NOT NULL AUTO_INCREMENT,
	EAS_Nombre VARCHAR(250),
	EAS_Eliminado BOOL,
	PRIMARY KEY (EAS_Id)
) 
;


CREATE TABLE MPS_EmpresaCotizadora
(
	ECO_Id INTEGER NOT NULL AUTO_INCREMENT,
	ECO_Nombre NVARCHAR(250),
	ECO_Eliminado BOOL,
	PRIMARY KEY (ECO_Id)
) 
;


CREATE TABLE MPS_Persona
(
	PER_Id INTEGER NOT NULL AUTO_INCREMENT,
	PER_Nombres VARCHAR(250),
	PER_ApellidoMaterno VARCHAR(250),
	PER_ApellidoPaterno VARCHAR(250),
	PAR_IdSexo INTEGER,
	PER_FechaNacimiento DATETIME,
	PER_Identificacion BIGINT,
	PER_IdentificacionDV VARCHAR(1),
	PER_TelefonoCelular VARCHAR(100),
	PER_Email VARCHAR(250),
	PER_Eliminado BOOL,
	PRIMARY KEY (PER_Id)
) 
;


CREATE TABLE MPS_Producto
(
	PRO_Id INTEGER NOT NULL AUTO_INCREMENT,
	PRO_Nombre VARCHAR(250),
	PRO_Codigo VARCHAR(250),
	PRO_Eliminado BOOL,
	PRIMARY KEY (PRO_Id)
) 
;


CREATE TABLE MPS_Region
(
	REG_Id INTEGER NOT NULL AUTO_INCREMENT,
	REG_Codigo INTEGER,
	REG_Nombre VARCHAR(250),
	REG_Eliminado BOOL,
	PRIMARY KEY (REG_Id)
) 
;



SET FOREIGN_KEY_CHECKS=1;


ALTER TABLE MAU_CotizacionAuto ADD CONSTRAINT FK_MAU_CotizacionAuto_MPS_Cotizacion 
	FOREIGN KEY (COT_Id) REFERENCES MPS_Cotizacion (COT_Id)
;

ALTER TABLE MAU_CotizacionAuto ADD CONSTRAINT FK_MAU_CotAuto_MPS_Com 
	FOREIGN KEY (COM_Id) REFERENCES MPS_Comuna (COM_Id)
;

ALTER TABLE MAU_CotizacionAuto ADD CONSTRAINT FK_MAU_CotizAuto_MPS_Per 
	FOREIGN KEY (PER_Id) REFERENCES MPS_Persona (PER_Id)
;

ALTER TABLE MAU_CotizacionAuto ADD CONSTRAINT FK_MAU_CotAuto_MAU_Mod 
	FOREIGN KEY (MOD_Id) REFERENCES MAU_Modelo (MOD_Id)
;

ALTER TABLE MAU_MarcaId ADD CONSTRAINT FK_MAU_MarcaId_MAU_Marca 
	FOREIGN KEY (MAR_Id) REFERENCES MAU_Marca (MAR_Id)
;

ALTER TABLE MAU_MarcaId ADD CONSTRAINT FK_MAU_MarId_MPS_EmpresaCot 
	FOREIGN KEY (ECO_Id) REFERENCES MPS_EmpresaCotizadora (ECO_Id)
;

ALTER TABLE MAU_Modelo ADD CONSTRAINT FK_MAU_Modelo_MAU_Marca 
	FOREIGN KEY (MAR_Id) REFERENCES MAU_Marca (MAR_Id)
;

ALTER TABLE MAU_ModeloId ADD CONSTRAINT FK_MAU_ModeloId_MAU_Modelo 
	FOREIGN KEY (MOD_Id) REFERENCES MAU_Modelo (MOD_Id)
;

ALTER TABLE MAU_ModeloId ADD CONSTRAINT FK_MAU_ModId_MPS_EmpresaCot 
	FOREIGN KEY (ECO_Id) REFERENCES MPS_EmpresaCotizadora (ECO_Id)
;

ALTER TABLE MPS_AseguradoraId ADD CONSTRAINT FK_MPS_AsegId_MPS_EmpAseg 
	FOREIGN KEY (EAS_Id) REFERENCES MPS_EmpresaAseguradora (EAS_Id)
;

ALTER TABLE MPS_AseguradoraId ADD CONSTRAINT FK_MPS_AsegId_MPS_EmpCot 
	FOREIGN KEY (ECO_Id) REFERENCES MPS_EmpresaCotizadora (ECO_Id)
;

ALTER TABLE MPS_Ciudad ADD CONSTRAINT FK_MPS_Ciudad_MPS_Region 
	FOREIGN KEY (REG_Id) REFERENCES MPS_Region (REG_Id)
;

ALTER TABLE MPS_Comuna ADD CONSTRAINT FK_MPS_Comuna_MPS_Ciudad 
	FOREIGN KEY (CIU_Id) REFERENCES MPS_Ciudad (CIU_Id)
;

ALTER TABLE MPS_Comuna ADD CONSTRAINT FK_MPS_Comuna_MPS_Region 
	FOREIGN KEY (REG_Id) REFERENCES MPS_Region (REG_Id)
;

ALTER TABLE MPS_Cotizacion ADD CONSTRAINT FK_MPS_Cotizacion_MPS_Producto 
	FOREIGN KEY (PRO_Id) REFERENCES MPS_Producto (PRO_Id)
;

ALTER TABLE MPS_Cotizacion ADD CONSTRAINT FK_MPS_Cot_MPS_EmpCot 
	FOREIGN KEY (ECO_Id) REFERENCES MPS_EmpresaCotizadora (ECO_Id)
;

ALTER TABLE MPS_CotizacionOferta ADD CONSTRAINT FK_MPS_CotizacionOferta_MPS_EmpresaAseguradora 
	FOREIGN KEY (EAS_Id) REFERENCES MPS_EmpresaAseguradora (EAS_Id)
;

ALTER TABLE MPS_CotizacionOferta ADD CONSTRAINT FK_MPS_CotOferta_MPS_Cot 
	FOREIGN KEY (COT_Id) REFERENCES MPS_Cotizacion (COT_Id)
;
